// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLo1PT_2_Yvw9h8qknWjyQWanN0Jq7Y_o',
    appId: '1:1050869517460:web:7e4d71bcb2f72f8a4bf881',
    messagingSenderId: '1050869517460',
    projectId: 'beyond-barrier',
    authDomain: 'beyond-barrier.firebaseapp.com',
    storageBucket: 'beyond-barrier.firebasestorage.app',
    measurementId: 'G-486MMJGYN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYQHCk8CLBe-aKpraz1-GiW1Jbu7_g1vQ',
    appId: '1:1050869517460:android:b16491cbfa8908814bf881',
    messagingSenderId: '1050869517460',
    projectId: 'beyond-barrier',
    storageBucket: 'beyond-barrier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChKwsnH05RuGpVqSZJ99U6c25VlLZ15F0',
    appId: '1:1050869517460:ios:5ffcf02cc40fa5b54bf881',
    messagingSenderId: '1050869517460',
    projectId: 'beyond-barrier',
    storageBucket: 'beyond-barrier.firebasestorage.app',
    iosBundleId: 'com.example.bb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChKwsnH05RuGpVqSZJ99U6c25VlLZ15F0',
    appId: '1:1050869517460:ios:5ffcf02cc40fa5b54bf881',
    messagingSenderId: '1050869517460',
    projectId: 'beyond-barrier',
    storageBucket: 'beyond-barrier.firebasestorage.app',
    iosBundleId: 'com.example.bb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLo1PT_2_Yvw9h8qknWjyQWanN0Jq7Y_o',
    appId: '1:1050869517460:web:6e66ff9fb5bd48174bf881',
    messagingSenderId: '1050869517460',
    projectId: 'beyond-barrier',
    authDomain: 'beyond-barrier.firebaseapp.com',
    storageBucket: 'beyond-barrier.firebasestorage.app',
    measurementId: 'G-H3DN27V91E',
  );
}
